name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello thank you for your contribution, do not worry, I will review this issues in a few days at the latest.'
        pr-message: 'Hello thank you for your contribution, do not worry, I will review this pull request in a few days at the latest.'
