# This is a basic workflow to help you get started with Actions

name: log

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: git clone
        run: git clone https://github.com/KomeilParseh/mozlink && cd mozlink

      - name: git configuration
        run: |

          git config --global user.email "you@example.com"
          git config --global user.name "linter"

      - name: Write logs
        run: |

          git log > gitLog
          git add gitLog
          git commit -m "git log file"
          git push
