# This is a basic workflow to help you get started with Actions

name: one fetch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install one fetch
        run: |
 
          git config --global user.name 'oneFetch[bot]'
          git config --global user.email 'komeilparseh@users.noreply.github.com'

          sudo add-apt-repository ppa:o2sh/onefetch -y
          sudo apt-get update -y; sudo apt upgrade -y
          
          sudo apt-get install onefetch -y

      # Runs a set of commands using the runners shell
      - name: Run one fetch
        run: |
          onefetch > COMMIT.md
          git commit -am "COMMIT.md"
          git push
